name: Test Ubuntu on Pull Request

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Test Ubuntu Startup Scripts
        shell: bash
        run: |
          ./ubuntu/scripts/install.sh
